# Cloudflare Pages 配置文件
name = "chase-game"
compatibility_date = "2024-01-01"

[env.production]
# 生产环境配置
# 你可以在这里添加环境变量

[env.preview]
# 预览环境配置

# Pages 项目配置
[pages]
# 构建输出目录
output_dir = "build"
# 构建命令（如果需要）
# build_command = "echo 'Unity build already completed'"
